const affirmations = [
   "you are blooming in your own time",
  "soft days are still progress",
  "you are gentle and that is powerful",
  "rest is part of the process",
  "small steps still move you forward",
  "your worth is not measured by productivity",
  "you bring light just by being here",
  "it’s okay to move slow",
  "you are allowed to take up space",
  "your softness is your strength",
  "progress, not perfection",
  "you deserve calm mornings",
  "you are doing better than you think",
  "slow growth is still growth",
  "your presence is a gift",
  "tiny seeds become wildflowers",
  "you are enough exactly as you are",
  "there’s no rush to bloom",
  "your journey is your own",
  "the sun always returns",
  "you are a calm in the storm",
  "you carry peace inside you",
  "your kindness is contagious",
  "gentle hearts move mountains",
  "you are a safe harbor",
  "breathe deeply, you are home",
  "softness is a quiet strength",
  "you deserve gentle love",
  "your story is still unfolding",
  "hope blooms in stillness",
  "you are worthy of rest",
  "you shine even on cloudy days",
  "every petal opens in its own time",
  "your light is a warm glow",
  "you are rooted and growing",
  "calmness flows through you",
  "your heart beats a gentle rhythm",
  "you are more than enough",
  "you are a tender soul",
  "each day is a fresh start",
  "your dreams are valid and true",
  "soft moments nourish your spirit",
  "you bring beauty to the world",
  "you are gentle like a morning breeze",
  "your spirit blooms quietly",
  "peace begins within you",
  "you are wrapped in kindness",
  "you are growing at your own pace",
  "you have a soft and steady strength",
  "you deserve moments of stillness",
  "your gentle soul is a light",
  "you are surrounded by love",
  "you are worthy of care",
  "you make the world softer",
  "your heart is a quiet garden",
  "you are blooming beautifully",
  "your kindness creates ripples",
  "rest fuels your growth",
  "you are a calming presence",
  "your calm is contagious",
  "gentle love heals deeply",
  "you are patient with yourself",
  "you shine with quiet grace",
  "each breath brings peace",
  "you are growing like wildflowers",
  "soft hearts are brave hearts",
  "you are enough every moment",
  "you deserve time to breathe",
  "your warmth comforts others",
  "you are a gift to this world",
  "you are learning and blossoming",
  "your soul is wrapped in light",
  "gentle hands can move mountains",
  "you are kind to yourself",
  "soft moments bring strength",
  "you are a peaceful warrior",
  "your presence is calming",
  "you are loved for who you are",
  "you carry grace within",
  "your spirit shines softly",
  "you are treasured and loved",
  "you are worthy of quiet joy",
  "your light touches others",
  "gentle days heal deeply",
  "you are patient with growth",
  "you deserve love and rest",
  "your calm spirit inspires",
  "you bring peace to chaos",
  "you are a soft light in darkness",
  "your heart is full of kindness",
  "you are growing quietly strong",
  "gentle strength is enduring",
  "you are a breath of fresh air",
  "your soul sings softly",
  "you deserve gentle moments",
  "you are wrapped in gentle grace",
  "your presence soothes others",
  "you are a calm steady flame",
  "softness is your power",
  "you are becoming beautifully",
  "your heart beats with courage",
  "you carry love with you",
  "you are a quiet strength",
  "gentle words heal wounds",
  "you are enough as you are",
  "your spirit is tender and strong",
  "you bring light without trying",
  "you are a calm in a busy world",
  "your kindness is your crown",
  "you deserve peace and love",
  "you are growing with grace",
  "your soul is full of hope",
  "you are soft yet unbreakable",
  "gentle love changes the world",
  "you are worthy of rest and joy",
  "your calm heart guides you",
  "you carry quiet strength daily",
  "you are gentle with yourself",
  "your presence is a soothing balm",
  "you are light in the quiet",
  "you are blooming in stillness",
  "your soul is wrapped in calm",
  "gentle hearts shine the brightest",
  "you are a treasure to many",
  "you deserve kind thoughts",
  "you are healing with time",
  "your spirit flows with grace",
  "you carry softness with strength",
  "you are growing through quiet days",
  "gentle care heals your soul",
  "you are a peaceful presence",
  "your heart is a soft home",
  "you are a calm breeze",
  "you deserve quiet moments",
  "your light shines even quietly",
  "you are becoming who you are meant to be",
  "gentle souls are fierce and brave",
  "you are surrounded by calm",
  "you carry hope within",
  "your spirit blooms with kindness",
  "you are a soft whisper of love",
  "you deserve gentle rest",
  "you are a light that never fades",
  "your calm is your gift",
  "you are growing with patience",
  "gentle strength carries you far",
  "you are soft and brave",
  "your heart beats with quiet power",
  "you deserve peace every day",
  "you are a gentle ray of sunshine",
  "your spirit shines through softly",
  "you carry calm wherever you go",
  "you are blossoming beautifully",
  "gentle moments heal deeply",
  "you are enough, always",
  "your kindness lights the way",
  "you are patient with your journey",
  "your calm heart is your compass",
  "you deserve love and peace",
  "you are a quiet light in the dark",
  "your soul is soft and strong",
  "gentle care nurtures you",
  "you are growing through love",
  "you carry kindness with you",
  "you are a peaceful soul",
  "your presence calms others",
  "you deserve soft hugs and warmth",
  "you are blooming like spring flowers",
  "gentle hearts bring healing",
  "you are enough exactly now",
  "your spirit flows with calmness",
  "you carry peace in your breath",
  "you are a soft melody",
  "your heart is wrapped in love",
  "you deserve quiet joy",
  "you are becoming beautifully strong",
  "gentle strength is your nature",
  "you are a calm oasis",
  "your light is soft but powerful",
  "you carry hope in your smile",
  "you are blooming with grace",
  "gentle moments bring strength",
  "you are a gift to yourself",
  "your soul shines quietly",
  "you deserve gentle love daily",
  "you are growing in kindness",
  "your calm spirit comforts many",
  "you carry softness in your soul",
  "you are a quiet beacon",
  "your heart beats with love",
  "you deserve gentle care",
  "you are blossoming with patience",
  "gentle words soothe your soul",
  "you are enough in every way",
  "your spirit flows gently",
  "you carry peace like a flower",
  "you are a soft light",
  "your calm heart guides your path",
  "you deserve rest and kindness",
  "you are growing through stillness",
  "gentle love fills your soul",
  "you are a peaceful light",
  "your presence brings calm",
  "you carry hope gently",
  "you are blooming quietly",
  "your heart is a gentle garden",
  "you deserve soft moments",
  "you are becoming softly strong",
  "gentle strength shines through",
  "you are a calm and steady flame",
  "your light is gentle but bright",
  "you carry love quietly",
  "you are blooming like the dawn",
  "gentle moments heal your heart",
  "you are enough as you grow",
  "your spirit is soft and bright",
  "you deserve gentle rest",
  "you are growing with love",
  "your calm soul comforts many",
  "you carry kindness within",
  "you are a quiet light in the world",
  "your heart beats with gentle strength",
  "you deserve peaceful days",
  "you are blossoming with grace",
  "gentle love guides you",
  "you are a soft and steady light",
  "your presence is soothing",
  "you carry calmness daily",
  "you are blooming beautifully inside",
  "your spirit flows with love",
  "you deserve soft and quiet joy",
  "you are growing gently",
  "gentle strength lives in you",
  "you are a calm and loving soul",
  "your light shines softly",
  "you carry hope quietly",
  "you are blooming with peace",
  "gentle moments nourish your heart",
  "you are enough in this moment",
  "your spirit is calm and kind",
  "you deserve gentle care and love",
  "you are growing with patience and grace",
  "your calm heart comforts those around you",
  "you carry kindness softly",
  "you are a quiet beacon of love",
  "your heart beats with peaceful strength",
  "you deserve rest and gentle moments",
  "you are blossoming quietly with grace"
];

// get daily affirmation based on date
function getDailyAffirmation() {
  const today = new Date();
  const index = today.getFullYear() * 366 + today.getMonth() * 31 + today.getDate();
  return affirmations[index % affirmations.length];
}

function setTheme(textColor) {
  const widget = document.querySelector('.widget');
  widget.style.color = textColor; // this changes text + leaf color
}

function displayAffirmation() {
  const affirmationText = getDailyAffirmation();
  document.getElementById('affirmation-text').textContent = affirmationText;
}

// setup color pickers
document.querySelectorAll('.color-circle').forEach(circle => {
  circle.addEventListener('click', () => {
    const textColor = circle.getAttribute('data-text');
    setTheme(textColor);
  });
});

// initial load
displayAffirmation();
setTheme('#5a513f'); // default beige text & leaf color
